spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ENC(rKm9/9/n45lKYAD+WkPhcg==)
    password: ENC(rKm9/9/n45lKYAD+WkPhcg==)
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  pattern:
    console: '%-5level %d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} - %msg%n'
    file: '%-5level %d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} - %msg%n'
  file:
    name: logFiles/app.log
jasypt:
  encryptor:
    password: ${PASSWORD}
    algorithm: ${ALGORITHM}
server:
  port: 8081
